# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/nucleo/odometry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goldo.common import geometry_pb2 as goldo_dot_common_dot_geometry__pb2
from goldo import pb2_options_pb2 as goldo_dot_pb2__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/nucleo/odometry.proto',
  package='goldo.nucleo.odometry',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1bgoldo/nucleo/odometry.proto\x12\x15goldo.nucleo.odometry\x1a\x1bgoldo/common/geometry.proto\x1a\x17goldo/pb2_options.proto\"\xc6\x01\n\x0eOdometryConfig\x12\x1b\n\x13\x64ist_per_count_left\x18\x01 \x01(\x02\x12\x1c\n\x14\x64ist_per_count_right\x18\x02 \x01(\x02\x12\x1b\n\x13wheel_distance_left\x18\x03 \x01(\x02\x12\x1c\n\x14wheel_distance_right\x18\x04 \x01(\x02\x12\x1e\n\x16speed_filter_frequency\x18\x05 \x01(\x02\x12\x1e\n\x16\x61\x63\x63\x65l_filter_frequency\x18\x06 \x01(\x02\x62\x06proto3')
  ,
  dependencies=[goldo_dot_common_dot_geometry__pb2.DESCRIPTOR,goldo_dot_pb2__options__pb2.DESCRIPTOR,])




_ODOMETRYCONFIG = _descriptor.Descriptor(
  name='OdometryConfig',
  full_name='goldo.nucleo.odometry.OdometryConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dist_per_count_left', full_name='goldo.nucleo.odometry.OdometryConfig.dist_per_count_left', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dist_per_count_right', full_name='goldo.nucleo.odometry.OdometryConfig.dist_per_count_right', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wheel_distance_left', full_name='goldo.nucleo.odometry.OdometryConfig.wheel_distance_left', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wheel_distance_right', full_name='goldo.nucleo.odometry.OdometryConfig.wheel_distance_right', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='speed_filter_frequency', full_name='goldo.nucleo.odometry.OdometryConfig.speed_filter_frequency', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='accel_filter_frequency', full_name='goldo.nucleo.odometry.OdometryConfig.accel_filter_frequency', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=307,
)

DESCRIPTOR.message_types_by_name['OdometryConfig'] = _ODOMETRYCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OdometryConfig = _reflection.GeneratedProtocolMessageType('OdometryConfig', (_message.Message,), dict(
  DESCRIPTOR = _ODOMETRYCONFIG,
  __module__ = 'goldo.nucleo.odometry_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.odometry.OdometryConfig)
  ))
_sym_db.RegisterMessage(OdometryConfig)


# @@protoc_insertion_point(module_scope)
