# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/nucleo/propulsion.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/nucleo/propulsion.proto',
  package='goldorak.nucleo.propulsion',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dgoldo/nucleo/propulsion.proto\x12\x1agoldorak.nucleo.propulsion\"\x83\x01\n\x17MotorsVelocitySetpoints\x12\x10\n\x08left_vel\x18\x01 \x01(\x02\x12\x11\n\tright_vel\x18\x02 \x01(\x02\x12 \n\x18left_current_feedforward\x18\x03 \x01(\x02\x12!\n\x19right_current_feedforward\x18\x04 \x01(\x02\"\xc3\x01\n\x0eOdometryConfig\x12\x17\n\x0f\x65ncoders_period\x18\x01 \x01(\x05\x12\x1b\n\x13\x64ist_per_count_left\x18\x02 \x01(\x02\x12\x1c\n\x14\x64ist_per_count_right\x18\x03 \x01(\x02\x12\x16\n\x0ewheels_spacing\x18\x04 \x01(\x02\x12\x1e\n\x16speed_filter_frequency\x18\x05 \x01(\x02\x12%\n\x1d\x61\x63\x63\x65leration_filter_frequency\x18\x06 \x01(\x02\x62\x06proto3'
)




_MOTORSVELOCITYSETPOINTS = _descriptor.Descriptor(
  name='MotorsVelocitySetpoints',
  full_name='goldorak.nucleo.propulsion.MotorsVelocitySetpoints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_vel', full_name='goldorak.nucleo.propulsion.MotorsVelocitySetpoints.left_vel', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_vel', full_name='goldorak.nucleo.propulsion.MotorsVelocitySetpoints.right_vel', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_current_feedforward', full_name='goldorak.nucleo.propulsion.MotorsVelocitySetpoints.left_current_feedforward', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_current_feedforward', full_name='goldorak.nucleo.propulsion.MotorsVelocitySetpoints.right_current_feedforward', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=193,
)


_ODOMETRYCONFIG = _descriptor.Descriptor(
  name='OdometryConfig',
  full_name='goldorak.nucleo.propulsion.OdometryConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='encoders_period', full_name='goldorak.nucleo.propulsion.OdometryConfig.encoders_period', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dist_per_count_left', full_name='goldorak.nucleo.propulsion.OdometryConfig.dist_per_count_left', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dist_per_count_right', full_name='goldorak.nucleo.propulsion.OdometryConfig.dist_per_count_right', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wheels_spacing', full_name='goldorak.nucleo.propulsion.OdometryConfig.wheels_spacing', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='speed_filter_frequency', full_name='goldorak.nucleo.propulsion.OdometryConfig.speed_filter_frequency', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='acceleration_filter_frequency', full_name='goldorak.nucleo.propulsion.OdometryConfig.acceleration_filter_frequency', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=391,
)

DESCRIPTOR.message_types_by_name['MotorsVelocitySetpoints'] = _MOTORSVELOCITYSETPOINTS
DESCRIPTOR.message_types_by_name['OdometryConfig'] = _ODOMETRYCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotorsVelocitySetpoints = _reflection.GeneratedProtocolMessageType('MotorsVelocitySetpoints', (_message.Message,), {
  'DESCRIPTOR' : _MOTORSVELOCITYSETPOINTS,
  '__module__' : 'goldo.nucleo.propulsion_pb2'
  # @@protoc_insertion_point(class_scope:goldorak.nucleo.propulsion.MotorsVelocitySetpoints)
  })
_sym_db.RegisterMessage(MotorsVelocitySetpoints)

OdometryConfig = _reflection.GeneratedProtocolMessageType('OdometryConfig', (_message.Message,), {
  'DESCRIPTOR' : _ODOMETRYCONFIG,
  '__module__' : 'goldo.nucleo.propulsion_pb2'
  # @@protoc_insertion_point(class_scope:goldorak.nucleo.propulsion.OdometryConfig)
  })
_sym_db.RegisterMessage(OdometryConfig)


# @@protoc_insertion_point(module_scope)
