# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/nucleo/robot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/nucleo/robot.proto',
  package='goldo.nucleo.robot',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18goldo/nucleo/robot.proto\x12\x12goldo.nucleo.robot\"\x1f\n\x0f\x43onfigLoadBegin\x12\x0c\n\x04size\x18\x01 \x01(\x05\"\x1f\n\x0f\x43onfigLoadChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x1c\n\rConfigLoadEnd\x12\x0b\n\x03\x63rc\x18\x01 \x01(\x05\x62\x06proto3'
)




_CONFIGLOADBEGIN = _descriptor.Descriptor(
  name='ConfigLoadBegin',
  full_name='goldo.nucleo.robot.ConfigLoadBegin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='goldo.nucleo.robot.ConfigLoadBegin.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=79,
)


_CONFIGLOADCHUNK = _descriptor.Descriptor(
  name='ConfigLoadChunk',
  full_name='goldo.nucleo.robot.ConfigLoadChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='goldo.nucleo.robot.ConfigLoadChunk.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=112,
)


_CONFIGLOADEND = _descriptor.Descriptor(
  name='ConfigLoadEnd',
  full_name='goldo.nucleo.robot.ConfigLoadEnd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='crc', full_name='goldo.nucleo.robot.ConfigLoadEnd.crc', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['ConfigLoadBegin'] = _CONFIGLOADBEGIN
DESCRIPTOR.message_types_by_name['ConfigLoadChunk'] = _CONFIGLOADCHUNK
DESCRIPTOR.message_types_by_name['ConfigLoadEnd'] = _CONFIGLOADEND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigLoadBegin = _reflection.GeneratedProtocolMessageType('ConfigLoadBegin', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGLOADBEGIN,
  '__module__' : 'goldo.nucleo.robot_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.robot.ConfigLoadBegin)
  })
_sym_db.RegisterMessage(ConfigLoadBegin)

ConfigLoadChunk = _reflection.GeneratedProtocolMessageType('ConfigLoadChunk', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGLOADCHUNK,
  '__module__' : 'goldo.nucleo.robot_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.robot.ConfigLoadChunk)
  })
_sym_db.RegisterMessage(ConfigLoadChunk)

ConfigLoadEnd = _reflection.GeneratedProtocolMessageType('ConfigLoadEnd', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGLOADEND,
  '__module__' : 'goldo.nucleo.robot_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.robot.ConfigLoadEnd)
  })
_sym_db.RegisterMessage(ConfigLoadEnd)


# @@protoc_insertion_point(module_scope)
