Sync=0
Heartbeat=1
Reset=2
CommStats=3
DbgPrintf=4

PropulsionTelemetry=8
PropulsionTelemetryEx=9
PropulsionStateChange=10

StartOfMatch=16
EndOfMatch=17

CmdEmergencyStop=32
CmdSelectSide=33
CmdEnterDebugMode=34
CmdExitDebugMode=35

DbgGetOdometryConfig=64
DbgSetOdometryConfig=65
DbgGetPropulsionConfig=66
DbgSetPropulsionConfig=67


DbgDynamixelsList=72
DbgDynamixelDescr=73
DbgDynamixelSetTorqueEnable=74
DbgDynamixelSetGoalPosition=75
DbgDynamixelSetTorqueLimit=76
DbgDynamixelGetRegisters=77
DbgDynamixelSetRegisters=78

DbgSetMotorsEnable=80
DbgSetMotorsPwm=81
DbgSetPropulsionEnable=82
DbgPropulsionSetPose=83
DbgPropulsionTest=84
DbgPropulsionExecuteTrajectory=85
DbgPropulsionExecuteRotation=86
DbgPropulsionExecuteReposition=87
DbgMiscRepositionStartGreen=100
DbgReset=127