---
enabled_tasks:
  - propulsion
  - odrive_comm
propulsion_task:
  motor_controller: ODriveUART
  update_period_ms: 1
  telemetry_period_ms: 20
  telemetry_ex_period_ms: 50
  pose_period_ms: 100

robot_simulator:
  speed_coeff: 2.0e-2
  wheels_spacing: 0.205
  encoders_spacing: 0.235
  encoders_counts_per_m: 0.5e+5
  encoders_period: 8192

odometry:
  dist_per_count_left: 1.5358e-05
  dist_per_count_right: 1.5342e-05
  wheel_distance_left: 235.5e-3
  wheel_distance_right: 0
  speed_filter_frequency: 100
  accel_filter_frequency: 50
  
propulsion:
  low_level_config:
    wheels_distance: 0.205
    motors_speed_factor: 50.5
  pid_configs:
  - longi:
      kp: 2e1
      ki: 0
      kd: 0
      lim_i: 0.2
      lim_d: 0
      out_min: -10
      out_max: 10
    speed:
      kp: 0.0
      ki: 0.0
      kd: 0.0
      lim_i: 0.2
      lim_d: 0.0
      out_min: -1.0
      out_max: 1.0
    yaw:
      kp: 3e1
      ki: 0
      kd: 0
      lim_i: 0.2
      lim_d: 0
      out_min: -10
      out_max: 10
    yaw_rate:
      kp: 0.0
      ki: 0
      kd: 0
      lim_i: 0.2
      lim_d: 0
      out_min: -1
      out_max: 1
  lookahead_time: 0.5
  lookahead_distance: 0.15
  static_pwm_limit: 10
  cruise_pwm_limit: 100
  reposition_pwm_limit: 10
servos:
  - name: bras_lat_gauche
    id: 11
    type: STANDARD
    max_speed: 10000
    max_torque: 10
    cw_limit: 7000 
    ccw_limit: 15000
  - name: bras_lat_droite
    id: 10
    type: STANDARD
    max_speed: 10000
    max_torque: 10
    cw_limit: 6950 
    ccw_limit: 15200
  - name: fanion
    id: 9
    type: STANDARD
    max_speed: 10000
    max_torque: 10
    cw_limit: 6950 
    ccw_limit: 15200
  - name: test
    id: 3
    type: DYNAMIXEL_AX12
    max_speed: 0x1020
    max_torque: 10
    cw_limit: 19000
    ccw_limit: 51000
#7 et 8 pales dynamixels
  
sensors:
  - name: start_match
    id: 3
  - name: emergency_stop
    id: 6
  - name: vacuostat
    id: 1
  - name: laser_droit
    id: 2
  - name: laser_gauche
    id: 0
  - name: rouge_gauche
    id: 4
  - name: rouge_droit
    id: 5

sequence_files:
  - "sequences/constants.txt"
