---
nucleo:
  enabled_tasks:
    - propulsion
    - odrive_comm
    - dynamixels_comm
    - fpga
    - servos
  propulsion_task:
    motor_controller: ODriveUART
    update_period_ms: 1
    telemetry_period_ms: 30
    telemetry_ex_period_ms: 200
    pose_period_ms: 100
    odrive_telemetry_period_ms: 500

  robot_simulator:
    speed_coeff: 2.0e-2
    wheels_spacing: 0.205
    encoders_spacing: 0.235
    encoders_counts_per_m: 0.5e+5
    encoders_period: 8192

  odometry:
    dist_per_count_left: 1.5345e-05
    dist_per_count_right: 1.5355e-05
    wheel_distance_left: 233.6e-3
    wheel_distance_right: 0
    speed_filter_frequency: 500
    accel_filter_frequency: 50

  propulsion:
    low_level_config:
      wheels_distance: 0.205
      motors_speed_factor: 50.5
    pid_configs:
    - longi:
        kp: 2e1
        ki: 0
        kd: 0
        lim_i: 0.2
        lim_d: 0
        out_min: -10
        out_max: 10
      speed:
        kp: 0.0
        ki: 0.0
        kd: 0.0
        lim_i: 0.2
        lim_d: 0.0
        out_min: -1.0
        out_max: 1.0
      yaw:
        kp: 2e1
        ki: 0
        kd: 0
        lim_i: 0.2
        lim_d: 0
        out_min: -10
        out_max: 10
      yaw_rate:
        kp: 0.0
        ki: 0
        kd: 0
        lim_i: 0.2
        lim_d: 0
        out_min: -1
        out_max: 1
    lookahead_time: 0.2
    lookahead_distance: 0.05
    static_motor_speed_limit: 100
    cruise_motor_speed_limit: 100
    reposition_motor_speed_limit: 10
    static_torque_limit: 0.6
    cruise_torque_limit: 0.6
    reposition_torque_limit: 0.06
  servos:
    - name: bras_lat_gauche
      id: 11
      type: STANDARD
      max_speed: 10000
      max_torque: 10
      cw_limit: 6800
      ccw_limit: 15000
    - name: bras_lat_droite
      id: 6
      type: STANDARD
      max_speed: 10000
      max_torque: 10
      cw_limit: 3500
      ccw_limit: 11800
    # Servo GS-9025MG (analog fils orange / rouge / marron)
    # - name: pince_gauche
    #   id: 8
    #   type: STANDARD
    #   max_speed: 20000
    #   max_torque: 10
    #   cw_limit: 6800
    #   ccw_limit: 14200
    # Servo GSD-9025MG (digital fils blanc / rouge / noir)
    - name: pince_gauche
      id: 8
      type: STANDARD
      max_speed: 20000
      max_torque: 10
      cw_limit: 5400
      ccw_limit: 12800
    - name: pince_droite
      id: 7
      type: STANDARD
      max_speed: 20000
      max_torque: 10
      cw_limit: 5000
      ccw_limit: 16000
    - name: fanion
      id: 10
      type: STANDARD
      max_speed: 10000
      max_torque: 10
      cw_limit: 8200
      ccw_limit: 11500
    - name: pale_g
      id: 7
      type: DYNAMIXEL_AX12
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 156
      ccw_limit: 657
    - name: pale_d
      id: 8
      type: DYNAMIXEL_AX12
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 364
      ccw_limit: 858
    - name: herse_v
      id: 81
      type: DYNAMIXEL_MX28
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 860
      ccw_limit: 2075
    - name: herse_slider
      id: 1
      type: DYNAMIXEL_AX12
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 140
      ccw_limit: 800
    - name: lift_left
      id: 0
      type: GOLDO_LIFT
      max_speed: 5000
      max_torque: 10
      cw_limit: 0
      ccw_limit: 2000
    - name: lift_right
      id: 1
      type: GOLDO_LIFT
      max_speed: 5000
      max_torque: 10
      cw_limit: 0
      ccw_limit: 2000
  sensors:
    - name: tirette
      type: NUCLEO
      id: 3
    - name: emergency_stop
      type: NUCLEO
      id: 6
    - name: recalage_ascensceur_gauche
      type: FPGA
      id: 14
    - name: recalage_ascensceur_droit
      type: FPGA
      id: 15
    - name: switch_pavillon
      type: FPGA
      id: 13
    - name: switch3
      type: FPGA
      id: 1
    - name: gache_g
      type: FPGA
      id: 10
    - name: gache_d
      type: FPGA
      id: 11
    - name: lr_cd
      type: FPGA
      id: 21
    - name: lr_cg
      type: FPGA
      id: 20
    - name: lr_ld
      type: FPGA
      id: 19
    - name: lr_lg
      type: FPGA
      id: 18
  lifts:
    - max_pwm: 0x20
      max_range: 1000
      kp: 0
      ki: 0
      kd: 0

  sequence_files:
    - "sequences/constants.txt"
