robot:
  propulsion:
    interface: ODRIVE_UART
    use_simulator: false
  geometry:
    front_length: 106.5
    back_length: 101.5
    outline:
      - [0,116.5]
      - [10,20]
robot_simulator:
  speed_coeff: 1
  wheels_spacing: 0.3
  encoders_spacing: 0.235
  encoders_counts_per_m: 0.5e+5
  encoders_period: 8192
odometry:
  dist_per_count_left: 1.5358e-05
  dist_per_count_right: 1.5342e-05
  wheel_distance_left: 235.5e-3
  wheel_distance_right: 0
  speed_filter_frequency: 100
  accel_filter_frequency: 50
  
propulsion:
  low_level_config:
    wheels_distance: 0.205
    motors_speed_factor: 50.5
  pid_configs:
  - longi:
      kp: 1
      ki: 0
      kd: 0
      lim_i: 0.2
      lim_d: 0
      out_min: -1
      out_max: 1
    speed:
      kp: 1.0
      ki: 0.0
      kd: 0.0
      lim_i: 0.2
      lim_d: 0.0
      out_min: -1.0
      out_max: 1.0
    yaw:
      kp: 0.5
      ki: 0
      kd: 0
      lim_i: 0.2
      lim_d: 0
      out_min: -1
      out_max: 1
    yaw_rate:
      kp: 0.2
      ki: 0
      kd: 0
      lim_i: 0.2
      lim_d: 0
      out_min: -1
      out_max: 1
  lookahead_time: 0.5
  lookahead_distance: 0.15
  static_pwm_limit: 10
  cruise_pwm_limit: 10
  reposition_pwm_limit: 10
dynamixels:
  - name: rail
    type: mx28
    id: 81
    cw_limit: 850
    ccw_limit: 1850    
    torque_limit: 512
  - name: coude
    id: 82
    type: mx28
    cw_limit: 800
    ccw_limit: 3150   
    torque_limit: 512
  - name: tete
    id: 1
    type: ax12
    cw_limit: 250
    ccw_limit: 850    
    torque_limit: 512
servos:
  - name: griffe_g
    id: 2
    max_speed: 40000
    cw_limit: 19000
    ccw_limit: 51000 
  - name: griffe_d
    id: 1
    max_speed: 40000
    cw_limit: 16000
    ccw_limit: 48000
  - name: stock_g
    id: 11
    max_speed: 40000
    cw_limit: 250
    ccw_limit: 850
  - name: stock_d
    id: 0
    max_speed: 40000
    cw_limit: 250
    ccw_limit: 850 
  - name: slider
    id: 10
    max_speed: 40000
    cw_limit: 32600
    ccw_limit: 45500
sensors:
  - name: micro_switch
    id: 0
  - name: vacuostat
    id: 1
  - name: laser_droit
    id: 2
  - name: laser_gauche
    id: 3
  - name: rouge_gauche
    id: 4
  - name: rouge_droit
    id: 5

sequence_files:
  - "sequences/constants.txt"
  - "sequences/waypoint_jaune.txt"
  - "sequences/waypoint_violet.txt"
  - "sequences/sequences.txt"
  - "sequences/tests.txt"
