---
nucleo:
  enabled_tasks:
    - propulsion
    - odrive_comm
    - dynamixels_comm
    - fpga
    - servos
  propulsion_task:
    motor_controller: ODriveUART
    update_period_ms: 1
    telemetry_period_ms: 30
    telemetry_ex_period_ms: 200
    pose_period_ms: 100
    odrive_telemetry_period_ms: 500

  robot_simulator:
    speed_coeff: 2.0e-2
    wheels_spacing: 0.205
    encoders_spacing: 0.235
    encoders_counts_per_m: 0.5e+5
    encoders_period: 8192

  odometry:
    dist_per_count_left: 1.5345e-05
    dist_per_count_right: 1.5355e-05
    wheel_distance_left: 233.6e-3
    wheel_distance_right: 0
    speed_filter_frequency: 500
    accel_filter_frequency: 50

  propulsion:
    low_level_config:
      wheels_distance: 0.205
      motors_speed_factor: 50.5
    pid_configs:
    - longi:
        kp: 2e1
        ki: 0
        kd: 0
        lim_i: 0.2
        lim_d: 0
        out_min: -10
        out_max: 10
      speed:
        kp: 0.0
        ki: 0.0
        kd: 0.0
        lim_i: 0.2
        lim_d: 0.0
        out_min: -1.0
        out_max: 1.0
      yaw:
        kp: 2e1
        ki: 0
        kd: 0
        lim_i: 0.2
        lim_d: 0
        out_min: -10
        out_max: 10
      yaw_rate:
        kp: 0.0
        ki: 0
        kd: 0
        lim_i: 0.2
        lim_d: 0
        out_min: -1
        out_max: 1
    lookahead_time: 0.2
    lookahead_distance: 0.05
    static_motor_speed_limit: 100
    cruise_motor_speed_limit: 100
    reposition_motor_speed_limit: 10
    static_torque_limit: 0.6
    cruise_torque_limit: 0.6
    reposition_torque_limit: 0.06
  servos:
    - name: ejecteur
      id: 11
      type: STANDARD
      max_speed: 10000
      max_torque: 10
      cw_limit: 6800
      ccw_limit: 15000
    # Servo GS-9025MG (analog fils orange / rouge / marron)
    # - name: pince_gauche
    #   id: 8
    #   type: STANDARD
    #   max_speed: 20000
    #   max_torque: 10
    #   cw_limit: 6800
    #   ccw_limit: 14200
    # Servo GSD-9025MG (digital fils blanc / rouge / noir)

    # Bras G
    - name: epaule_g
      id: 83
      type: DYNAMIXEL_MX28
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 917
      ccw_limit: 3316
    - name: coude_g
      id: 3
      type: DYNAMIXEL_AX12
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 53
      ccw_limit: 833

    # Bras D
    - name: epaule_d
      id: 81
      type: DYNAMIXEL_MX28
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 766
      ccw_limit: 3171
    - name: coude_d
      id: 1
      type: DYNAMIXEL_AX12
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 184
      ccw_limit: 983

    # Pince ravisseuse
    - name: lift_pince
      id: 85
      type: DYNAMIXEL_MX28
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 289
      ccw_limit: 3867
    - name: mors_g
      id: 5
      type: DYNAMIXEL_AX12
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 0
      ccw_limit: 1023
    - name: chariot_g
      id: 6
      type: DYNAMIXEL_AX12
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 0
      ccw_limit: 1023
    - name: chariot_d
      id: 7
      type: DYNAMIXEL_AX12
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 0
      ccw_limit: 1023
    - name: mors_d
      id: 8
      type: DYNAMIXEL_AX12
      max_speed: 0x3ff
      max_torque: 0x3ff
      cw_limit: 0
      ccw_limit: 1023
      
    # Ascenseurs
    - name: lift_left
      id: 0
      type: GOLDO_LIFT
      max_speed: 5000
      max_torque: 10
      cw_limit: 0
      ccw_limit: 2000
    - name: lift_right
      id: 1
      type: GOLDO_LIFT
      max_speed: 5000
      max_torque: 10
      cw_limit: 0
      ccw_limit: 2000
  sensors:
    - name: tirette
      type: NUCLEO
      id: 3
    - name: emergency_stop
      type: NUCLEO
      id: 6
    - name: recalage_ascensceur_gauche
      type: FPGA
      id: 14
    - name: recalage_ascensceur_droit
      type: FPGA
      id: 15
    - name: switch_ejecteur
      type: FPGA
      id: 13
    - name: sick_bras_g
      type: FPGA
      id: 1
    - name: sick_bras_d
      type: FPGA
      id: 1
    - name: sick_lat_g
      type: FPGA
      id: 1
    - name: sick_lat_d
      type: FPGA
      id: 1
    - name: baumer_proche
      type: FPGA
      id: 1
    - name: baumer_loin
      type: FPGA
      id: 1
    - name: hall_statuette
      type: FPGA
      id: 1
    - name: tryohm_bit_0
      type: FPGA
      id: 1
    - name: tryohm_bit_1
      type: FPGA
      id: 1
  lifts:
    - max_pwm: 0x20
      max_range: 1000
      kp: 0
      ki: 0
      kd: 0

  sequence_files:
    - "sequences/constants.txt"
