# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/nucleo/robot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goldo import pb2_options_pb2 as goldo_dot_pb2__options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/nucleo/robot.proto',
  package='goldo.nucleo.robot',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18goldo/nucleo/robot.proto\x12\x12goldo.nucleo.robot\x1a\x17goldo/pb2_options.proto\"%\n\x0f\x43onfigLoadBegin\x12\x12\n\x04size\x18\x01 \x01(\x05\x42\x04\x80\xb5\x18\x05\"\x1f\n\x0f\x43onfigLoadChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\"\n\rConfigLoadEnd\x12\x11\n\x03\x63rc\x18\x01 \x01(\x05\x42\x04\x80\xb5\x18\x05\"v\n\x10\x43onfigLoadStatus\x12\x41\n\x06status\x18\x01 \x01(\x0e\x32+.goldo.nucleo.robot.ConfigLoadStatus.StatusB\x04\x80\xb5\x18\x03\"\x1f\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\r\n\tCRC_ERROR\x10\x01\x62\x06proto3'
  ,
  dependencies=[goldo_dot_pb2__options__pb2.DESCRIPTOR,])



_CONFIGLOADSTATUS_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='goldo.nucleo.robot.ConfigLoadStatus.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CRC_ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=268,
  serialized_end=299,
)
_sym_db.RegisterEnumDescriptor(_CONFIGLOADSTATUS_STATUS)


_CONFIGLOADBEGIN = _descriptor.Descriptor(
  name='ConfigLoadBegin',
  full_name='goldo.nucleo.robot.ConfigLoadBegin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='goldo.nucleo.robot.ConfigLoadBegin.size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\200\265\030\005', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=110,
)


_CONFIGLOADCHUNK = _descriptor.Descriptor(
  name='ConfigLoadChunk',
  full_name='goldo.nucleo.robot.ConfigLoadChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='goldo.nucleo.robot.ConfigLoadChunk.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=143,
)


_CONFIGLOADEND = _descriptor.Descriptor(
  name='ConfigLoadEnd',
  full_name='goldo.nucleo.robot.ConfigLoadEnd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='crc', full_name='goldo.nucleo.robot.ConfigLoadEnd.crc', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\200\265\030\005', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=179,
)


_CONFIGLOADSTATUS = _descriptor.Descriptor(
  name='ConfigLoadStatus',
  full_name='goldo.nucleo.robot.ConfigLoadStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='goldo.nucleo.robot.ConfigLoadStatus.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\200\265\030\003', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONFIGLOADSTATUS_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=299,
)

_CONFIGLOADSTATUS.fields_by_name['status'].enum_type = _CONFIGLOADSTATUS_STATUS
_CONFIGLOADSTATUS_STATUS.containing_type = _CONFIGLOADSTATUS
DESCRIPTOR.message_types_by_name['ConfigLoadBegin'] = _CONFIGLOADBEGIN
DESCRIPTOR.message_types_by_name['ConfigLoadChunk'] = _CONFIGLOADCHUNK
DESCRIPTOR.message_types_by_name['ConfigLoadEnd'] = _CONFIGLOADEND
DESCRIPTOR.message_types_by_name['ConfigLoadStatus'] = _CONFIGLOADSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigLoadBegin = _reflection.GeneratedProtocolMessageType('ConfigLoadBegin', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGLOADBEGIN,
  '__module__' : 'goldo.nucleo.robot_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.robot.ConfigLoadBegin)
  })
_sym_db.RegisterMessage(ConfigLoadBegin)

ConfigLoadChunk = _reflection.GeneratedProtocolMessageType('ConfigLoadChunk', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGLOADCHUNK,
  '__module__' : 'goldo.nucleo.robot_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.robot.ConfigLoadChunk)
  })
_sym_db.RegisterMessage(ConfigLoadChunk)

ConfigLoadEnd = _reflection.GeneratedProtocolMessageType('ConfigLoadEnd', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGLOADEND,
  '__module__' : 'goldo.nucleo.robot_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.robot.ConfigLoadEnd)
  })
_sym_db.RegisterMessage(ConfigLoadEnd)

ConfigLoadStatus = _reflection.GeneratedProtocolMessageType('ConfigLoadStatus', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGLOADSTATUS,
  '__module__' : 'goldo.nucleo.robot_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.robot.ConfigLoadStatus)
  })
_sym_db.RegisterMessage(ConfigLoadStatus)


_CONFIGLOADBEGIN.fields_by_name['size']._options = None
_CONFIGLOADEND.fields_by_name['crc']._options = None
_CONFIGLOADSTATUS.fields_by_name['status']._options = None
# @@protoc_insertion_point(module_scope)
