---
robots:
  - robot1:
    hostname: '192.168.0.211'
    includes:
      - hal.yaml
      - nucleo.yaml
      - robot.yaml
  - robot2:
    hostname: '192.168.0.212'
    includes:
      - hal.yaml
      - nucleo.yaml
      - robot.yaml
      