geometry:
  front_length: 200
  back_length: 200
  outline:
    - [0,10]
    - [10,20]
odometry:
  dist_per_count_left: 1.9e-05
  encoder_period: 512
  update_period: 1e-3
  wheels_spacing: 0.5
propulsion:
  pid_speed:
    period: 10
    kp: 1
    ki: 1
    kd: 1
    feed_forward: 1
    lim_iterm: 0
    lim_determ: 0
    min_out: 0
    max_out: 0
  lookahead_time: 1
  lookahead_distance: 0.5
dynamixels:
  - name: slider
    id: 2
    cw_limit: 4095
    ccw_limit: 0    
    torque_limit: 512
  - name: arm
    id: 82
    cw_limit: 4095
    ccw_limit: 0    
    torque_limit: 512
  - name: wrist
    id: 83
    cw_limit: 4095
    ccw_limit: 0    
    torque_limit: 512
servos:
  - name: pince_bas
    cw_limit: 1000
    ccw_limit: 5000
    
