---
robot_geometry:
    front_length: 106.5
    back_length: 101.5
    configurations:
      - name: base
        front_length: 106.5
        back_length: 101.5
        outline:
          - { x: 0, y: 116.5}
          - { x: 10, y: 20}

rplidar:
  theta_offset: 145
  tresholds:
    near: 0.1
    mid: 0.3
    far: 0.5
