# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/camera.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/camera.proto',
  package='goldo.camera',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12goldo/camera.proto\x12\x0cgoldo.camera\"\x87\x01\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12.\n\x08\x65ncoding\x18\x03 \x01(\x0e\x32\x1c.goldo.camera.Image.Encoding\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"!\n\x08\x45ncoding\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04JPEG\x10\x01\"\xd6\x01\n\nDetections\x12\x36\n\ndetections\x18\x01 \x03(\x0b\x32\".goldo.camera.Detections.Detection\x1a\x8f\x01\n\tDetection\x12\x0e\n\x06tag_id\x18\x01 \x01(\x05\x12:\n\x07\x63orners\x18\x02 \x03(\x0b\x32).goldo.camera.Detections.Detection.Corner\x12\n\n\x02ux\x18\x03 \x01(\x02\x12\n\n\x02uy\x18\x04 \x01(\x02\x1a\x1e\n\x06\x43orner\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x62\x06proto3')
)



_IMAGE_ENCODING = _descriptor.EnumDescriptor(
  name='Encoding',
  full_name='goldo.camera.Image.Encoding',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JPEG', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=139,
  serialized_end=172,
)
_sym_db.RegisterEnumDescriptor(_IMAGE_ENCODING)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='goldo.camera.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='goldo.camera.Image.width', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='goldo.camera.Image.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='goldo.camera.Image.encoding', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='goldo.camera.Image.data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _IMAGE_ENCODING,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=172,
)


_DETECTIONS_DETECTION_CORNER = _descriptor.Descriptor(
  name='Corner',
  full_name='goldo.camera.Detections.Detection.Corner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='goldo.camera.Detections.Detection.Corner.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='goldo.camera.Detections.Detection.Corner.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=389,
)

_DETECTIONS_DETECTION = _descriptor.Descriptor(
  name='Detection',
  full_name='goldo.camera.Detections.Detection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tag_id', full_name='goldo.camera.Detections.Detection.tag_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='corners', full_name='goldo.camera.Detections.Detection.corners', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ux', full_name='goldo.camera.Detections.Detection.ux', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uy', full_name='goldo.camera.Detections.Detection.uy', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DETECTIONS_DETECTION_CORNER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=389,
)

_DETECTIONS = _descriptor.Descriptor(
  name='Detections',
  full_name='goldo.camera.Detections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detections', full_name='goldo.camera.Detections.detections', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DETECTIONS_DETECTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=389,
)

_IMAGE.fields_by_name['encoding'].enum_type = _IMAGE_ENCODING
_IMAGE_ENCODING.containing_type = _IMAGE
_DETECTIONS_DETECTION_CORNER.containing_type = _DETECTIONS_DETECTION
_DETECTIONS_DETECTION.fields_by_name['corners'].message_type = _DETECTIONS_DETECTION_CORNER
_DETECTIONS_DETECTION.containing_type = _DETECTIONS
_DETECTIONS.fields_by_name['detections'].message_type = _DETECTIONS_DETECTION
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
DESCRIPTOR.message_types_by_name['Detections'] = _DETECTIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), dict(
  DESCRIPTOR = _IMAGE,
  __module__ = 'goldo.camera_pb2'
  # @@protoc_insertion_point(class_scope:goldo.camera.Image)
  ))
_sym_db.RegisterMessage(Image)

Detections = _reflection.GeneratedProtocolMessageType('Detections', (_message.Message,), dict(

  Detection = _reflection.GeneratedProtocolMessageType('Detection', (_message.Message,), dict(

    Corner = _reflection.GeneratedProtocolMessageType('Corner', (_message.Message,), dict(
      DESCRIPTOR = _DETECTIONS_DETECTION_CORNER,
      __module__ = 'goldo.camera_pb2'
      # @@protoc_insertion_point(class_scope:goldo.camera.Detections.Detection.Corner)
      ))
    ,
    DESCRIPTOR = _DETECTIONS_DETECTION,
    __module__ = 'goldo.camera_pb2'
    # @@protoc_insertion_point(class_scope:goldo.camera.Detections.Detection)
    ))
  ,
  DESCRIPTOR = _DETECTIONS,
  __module__ = 'goldo.camera_pb2'
  # @@protoc_insertion_point(class_scope:goldo.camera.Detections)
  ))
_sym_db.RegisterMessage(Detections)
_sym_db.RegisterMessage(Detections.Detection)
_sym_db.RegisterMessage(Detections.Detection.Corner)


# @@protoc_insertion_point(module_scope)
