# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/nucleo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goldo import pb2_options_pb2 as goldo_dot_pb2__options__pb2
from goldo.nucleo import hal_pb2 as goldo_dot_nucleo_dot_hal__pb2
from goldo.nucleo import servos_pb2 as goldo_dot_nucleo_dot_servos__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/nucleo.proto',
  package='goldo.nucleo',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12goldo/nucleo.proto\x12\x0cgoldo.nucleo\x1a\x17goldo/pb2_options.proto\x1a\x16goldo/nucleo/hal.proto\x1a\x19goldo/nucleo/servos.proto\"j\n\x0cNucleoConfig\x12(\n\x03hal\x18\x01 \x01(\x0b\x32\x1b.goldo.nucleo.hal.HalConfig\x12\x30\n\x06servos\x18\x06 \x03(\x0b\x32 .goldo.nucleo.servos.ServoConfigb\x06proto3'
  ,
  dependencies=[goldo_dot_pb2__options__pb2.DESCRIPTOR,goldo_dot_nucleo_dot_hal__pb2.DESCRIPTOR,goldo_dot_nucleo_dot_servos__pb2.DESCRIPTOR,])




_NUCLEOCONFIG = _descriptor.Descriptor(
  name='NucleoConfig',
  full_name='goldo.nucleo.NucleoConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hal', full_name='goldo.nucleo.NucleoConfig.hal', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='servos', full_name='goldo.nucleo.NucleoConfig.servos', index=1,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=218,
)

_NUCLEOCONFIG.fields_by_name['hal'].message_type = goldo_dot_nucleo_dot_hal__pb2._HALCONFIG
_NUCLEOCONFIG.fields_by_name['servos'].message_type = goldo_dot_nucleo_dot_servos__pb2._SERVOCONFIG
DESCRIPTOR.message_types_by_name['NucleoConfig'] = _NUCLEOCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NucleoConfig = _reflection.GeneratedProtocolMessageType('NucleoConfig', (_message.Message,), {
  'DESCRIPTOR' : _NUCLEOCONFIG,
  '__module__' : 'goldo.nucleo_pb2'
  # @@protoc_insertion_point(class_scope:goldo.nucleo.NucleoConfig)
  })
_sym_db.RegisterMessage(NucleoConfig)


# @@protoc_insertion_point(module_scope)
