# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/path_planner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goldo.common import geometry_pb2 as goldo_dot_common_dot_geometry__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/path_planner.proto',
  package='goldo.path_planner',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x18goldo/path_planner.proto\x12\x12goldo.path_planner\x1a\x1bgoldo/common/geometry.proto\x1a\x19google/protobuf/any.proto\"M\n\x0fPathPlannerPath\x12,\n\x06points\x18\x01 \x03(\x0b\x32\x1c.goldo.common.geometry.Point\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x02\"\x84\x01\n\x12PathPlannerRequest\x12\x35\n\nstart_pose\x18\x01 \x01(\x0b\x32!.goldo.common.geometry.StaticPose\x12\x37\n\x0ctarget_poses\x18\x02 \x03(\x0b\x32!.goldo.common.geometry.StaticPose\"s\n\x13PathPlannerResponse\x12\x32\n\x05paths\x18\x01 \x03(\x0b\x32#.goldo.path_planner.PathPlannerPath\x12(\n\ndebug_info\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')
  ,
  dependencies=[goldo_dot_common_dot_geometry__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_PATHPLANNERPATH = _descriptor.Descriptor(
  name='PathPlannerPath',
  full_name='goldo.path_planner.PathPlannerPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='points', full_name='goldo.path_planner.PathPlannerPath.points', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cost', full_name='goldo.path_planner.PathPlannerPath.cost', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=181,
)


_PATHPLANNERREQUEST = _descriptor.Descriptor(
  name='PathPlannerRequest',
  full_name='goldo.path_planner.PathPlannerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start_pose', full_name='goldo.path_planner.PathPlannerRequest.start_pose', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_poses', full_name='goldo.path_planner.PathPlannerRequest.target_poses', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=316,
)


_PATHPLANNERRESPONSE = _descriptor.Descriptor(
  name='PathPlannerResponse',
  full_name='goldo.path_planner.PathPlannerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='paths', full_name='goldo.path_planner.PathPlannerResponse.paths', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='debug_info', full_name='goldo.path_planner.PathPlannerResponse.debug_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=433,
)

_PATHPLANNERPATH.fields_by_name['points'].message_type = goldo_dot_common_dot_geometry__pb2._POINT
_PATHPLANNERREQUEST.fields_by_name['start_pose'].message_type = goldo_dot_common_dot_geometry__pb2._STATICPOSE
_PATHPLANNERREQUEST.fields_by_name['target_poses'].message_type = goldo_dot_common_dot_geometry__pb2._STATICPOSE
_PATHPLANNERRESPONSE.fields_by_name['paths'].message_type = _PATHPLANNERPATH
_PATHPLANNERRESPONSE.fields_by_name['debug_info'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['PathPlannerPath'] = _PATHPLANNERPATH
DESCRIPTOR.message_types_by_name['PathPlannerRequest'] = _PATHPLANNERREQUEST
DESCRIPTOR.message_types_by_name['PathPlannerResponse'] = _PATHPLANNERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PathPlannerPath = _reflection.GeneratedProtocolMessageType('PathPlannerPath', (_message.Message,), dict(
  DESCRIPTOR = _PATHPLANNERPATH,
  __module__ = 'goldo.path_planner_pb2'
  # @@protoc_insertion_point(class_scope:goldo.path_planner.PathPlannerPath)
  ))
_sym_db.RegisterMessage(PathPlannerPath)

PathPlannerRequest = _reflection.GeneratedProtocolMessageType('PathPlannerRequest', (_message.Message,), dict(
  DESCRIPTOR = _PATHPLANNERREQUEST,
  __module__ = 'goldo.path_planner_pb2'
  # @@protoc_insertion_point(class_scope:goldo.path_planner.PathPlannerRequest)
  ))
_sym_db.RegisterMessage(PathPlannerRequest)

PathPlannerResponse = _reflection.GeneratedProtocolMessageType('PathPlannerResponse', (_message.Message,), dict(
  DESCRIPTOR = _PATHPLANNERRESPONSE,
  __module__ = 'goldo.path_planner_pb2'
  # @@protoc_insertion_point(class_scope:goldo.path_planner.PathPlannerResponse)
  ))
_sym_db.RegisterMessage(PathPlannerResponse)


# @@protoc_insertion_point(module_scope)
