# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/pb2_options.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/pb2_options.proto',
  package='goldo.pb2_options',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17goldo/pb2_options.proto\x12\x11goldo.pb2_options\x1a google/protobuf/descriptor.proto*\x9b\x01\n\x07\x43ppType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04\x42OOL\x10\x01\x12\x08\n\x04INT8\x10\x02\x12\t\n\x05UINT8\x10\x03\x12\t\n\x05INT16\x10\x04\x12\n\n\x06UINT16\x10\x05\x12\t\n\x05INT32\x10\x06\x12\n\n\x06UINT32\x10\x07\x12\t\n\x05INT64\x10\x08\x12\n\n\x06UINT64\x10\t\x12\t\n\x05\x46LOAT\x10\n\x12\n\n\x06\x44OUBLE\x10\x0b\x12\x08\n\x04VOID\x10\x0c:M\n\x08\x63pp_type\x12\x1d.google.protobuf.FieldOptions\x18\xd0\x86\x03 \x01(\x0e\x32\x1a.goldo.pb2_options.CppType:2\n\tmax_count\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x05:4\n\x0b\x66ixed_count\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_descriptor__pb2.DESCRIPTOR,])

_CPPTYPE = _descriptor.EnumDescriptor(
  name='CppType',
  full_name='goldo.pb2_options.CppType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BOOL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INT8', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UINT8', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INT16', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UINT16', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INT32', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UINT32', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INT64', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UINT64', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DOUBLE', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VOID', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=81,
  serialized_end=236,
)
_sym_db.RegisterEnumDescriptor(_CPPTYPE)

CppType = enum_type_wrapper.EnumTypeWrapper(_CPPTYPE)
UNKNOWN = 0
BOOL = 1
INT8 = 2
UINT8 = 3
INT16 = 4
UINT16 = 5
INT32 = 6
UINT32 = 7
INT64 = 8
UINT64 = 9
FLOAT = 10
DOUBLE = 11
VOID = 12

CPP_TYPE_FIELD_NUMBER = 50000
cpp_type = _descriptor.FieldDescriptor(
  name='cpp_type', full_name='goldo.pb2_options.cpp_type', index=0,
  number=50000, type=14, cpp_type=8, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
MAX_COUNT_FIELD_NUMBER = 50001
max_count = _descriptor.FieldDescriptor(
  name='max_count', full_name='goldo.pb2_options.max_count', index=1,
  number=50001, type=5, cpp_type=1, label=1,
  has_default_value=False, default_value=0,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)
FIXED_COUNT_FIELD_NUMBER = 50002
fixed_count = _descriptor.FieldDescriptor(
  name='fixed_count', full_name='goldo.pb2_options.fixed_count', index=2,
  number=50002, type=8, cpp_type=7, label=1,
  has_default_value=False, default_value=False,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key)

DESCRIPTOR.enum_types_by_name['CppType'] = _CPPTYPE
DESCRIPTOR.extensions_by_name['cpp_type'] = cpp_type
DESCRIPTOR.extensions_by_name['max_count'] = max_count
DESCRIPTOR.extensions_by_name['fixed_count'] = fixed_count
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

cpp_type.enum_type = _CPPTYPE
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(cpp_type)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(max_count)
google_dot_protobuf_dot_descriptor__pb2.FieldOptions.RegisterExtension(fixed_count)

# @@protoc_insertion_point(module_scope)
