# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/rplidar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/rplidar.proto',
  package='goldo.rplidar',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13goldo/rplidar.proto\x12\rgoldo.rplidar\"\x9f\x01\n\x05Zones\x12\x12\n\nfront_near\x18\x01 \x01(\x08\x12\x12\n\nright_near\x18\x02 \x01(\x08\x12\x11\n\tback_near\x18\x03 \x01(\x08\x12\x11\n\tleft_near\x18\x04 \x01(\x08\x12\x11\n\tfront_far\x18\x05 \x01(\x08\x12\x11\n\tright_far\x18\x06 \x01(\x08\x12\x10\n\x08\x62\x61\x63k_far\x18\x07 \x01(\x08\x12\x10\n\x08left_far\x18\x08 \x01(\x08\"3\n\tTresholds\x12\x0c\n\x04near\x18\x01 \x01(\x02\x12\x0b\n\x03mid\x18\x02 \x01(\x02\x12\x0b\n\x03\x66\x61r\x18\x03 \x01(\x02\x62\x06proto3'
)




_ZONES = _descriptor.Descriptor(
  name='Zones',
  full_name='goldo.rplidar.Zones',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='front_near', full_name='goldo.rplidar.Zones.front_near', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_near', full_name='goldo.rplidar.Zones.right_near', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='back_near', full_name='goldo.rplidar.Zones.back_near', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_near', full_name='goldo.rplidar.Zones.left_near', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='front_far', full_name='goldo.rplidar.Zones.front_far', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_far', full_name='goldo.rplidar.Zones.right_far', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='back_far', full_name='goldo.rplidar.Zones.back_far', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='left_far', full_name='goldo.rplidar.Zones.left_far', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=198,
)


_TRESHOLDS = _descriptor.Descriptor(
  name='Tresholds',
  full_name='goldo.rplidar.Tresholds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='near', full_name='goldo.rplidar.Tresholds.near', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mid', full_name='goldo.rplidar.Tresholds.mid', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='far', full_name='goldo.rplidar.Tresholds.far', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=251,
)

DESCRIPTOR.message_types_by_name['Zones'] = _ZONES
DESCRIPTOR.message_types_by_name['Tresholds'] = _TRESHOLDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Zones = _reflection.GeneratedProtocolMessageType('Zones', (_message.Message,), {
  'DESCRIPTOR' : _ZONES,
  '__module__' : 'goldo.rplidar_pb2'
  # @@protoc_insertion_point(class_scope:goldo.rplidar.Zones)
  })
_sym_db.RegisterMessage(Zones)

Tresholds = _reflection.GeneratedProtocolMessageType('Tresholds', (_message.Message,), {
  'DESCRIPTOR' : _TRESHOLDS,
  '__module__' : 'goldo.rplidar_pb2'
  # @@protoc_insertion_point(class_scope:goldo.rplidar.Tresholds)
  })
_sym_db.RegisterMessage(Tresholds)


# @@protoc_insertion_point(module_scope)
