# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goldo/table.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goldo.common import geometry_pb2 as goldo_dot_common_dot_geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goldo/table.proto',
  package='goldo.table',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11goldo/table.proto\x12\x0bgoldo.table\x1a\x1bgoldo/common/geometry.proto\"\x90\x01\n\x08\x43upState\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.goldo.table.CupType\x12\x30\n\x0borientation\x18\x02 \x01(\x0e\x32\x1b.goldo.table.CupOrientation\x12.\n\x08position\x18\x03 \x01(\x0b\x32\x1c.goldo.common.geometry.Point\"0\n\tReefState\x12#\n\x04\x63ups\x18\x01 \x03(\x0b\x32\x15.goldo.table.CupState\"\xd5\x01\n\nTableState\x12\x31\n\x05reefs\x18\x01 \x03(\x0b\x32\".goldo.table.TableState.ReefsEntry\x12#\n\x04\x63ups\x18\x02 \x01(\x0b\x32\x15.goldo.table.CupState\x12)\n\x06\x63ompas\x18\x03 \x01(\x0e\x32\x19.goldo.table.CompassState\x1a\x44\n\nReefsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12%\n\x05value\x18\x02 \x01(\x0b\x32\x16.goldo.table.ReefState:\x02\x38\x01*F\n\x07\x43upType\x12\x15\n\x11\x43UP_TYPE__UNKNOWN\x10\x00\x12\x12\n\x0e\x43UP_TYPE_GREEN\x10\x01\x12\x10\n\x0c\x43UP_TYPE_RED\x10\x02*i\n\x0e\x43upOrientation\x12\x1b\n\x17\x43UP_ORIENTATION_UNKNOWN\x10\x00\x12\x1c\n\x18\x43UP_ORIENTATION_STANDING\x10\x01\x12\x1c\n\x18\x43UP_ORIENTATION_UPTURNED\x10\x02*I\n\rWindsockState\x12\x14\n\x10WINDSOCK_UNKNOWN\x10\x00\x12\x0f\n\x0bWINDSOCK_UP\x10\x01\x12\x11\n\rWINDSOCK_DOWN\x10\x02*I\n\x0c\x43ompassState\x12\x13\n\x0f\x43OMPASS_UNKNOWN\x10\x00\x12\x11\n\rCOMPASS_NORTH\x10\x01\x12\x11\n\rCOMPASS_SOUTH\x10\x02\x62\x06proto3')
  ,
  dependencies=[goldo_dot_common_dot_geometry__pb2.DESCRIPTOR,])

_CUPTYPE = _descriptor.EnumDescriptor(
  name='CupType',
  full_name='goldo.table.CupType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CUP_TYPE__UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUP_TYPE_GREEN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUP_TYPE_RED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=476,
  serialized_end=546,
)
_sym_db.RegisterEnumDescriptor(_CUPTYPE)

CupType = enum_type_wrapper.EnumTypeWrapper(_CUPTYPE)
_CUPORIENTATION = _descriptor.EnumDescriptor(
  name='CupOrientation',
  full_name='goldo.table.CupOrientation',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CUP_ORIENTATION_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUP_ORIENTATION_STANDING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CUP_ORIENTATION_UPTURNED', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=548,
  serialized_end=653,
)
_sym_db.RegisterEnumDescriptor(_CUPORIENTATION)

CupOrientation = enum_type_wrapper.EnumTypeWrapper(_CUPORIENTATION)
_WINDSOCKSTATE = _descriptor.EnumDescriptor(
  name='WindsockState',
  full_name='goldo.table.WindsockState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='WINDSOCK_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WINDSOCK_UP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WINDSOCK_DOWN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=655,
  serialized_end=728,
)
_sym_db.RegisterEnumDescriptor(_WINDSOCKSTATE)

WindsockState = enum_type_wrapper.EnumTypeWrapper(_WINDSOCKSTATE)
_COMPASSSTATE = _descriptor.EnumDescriptor(
  name='CompassState',
  full_name='goldo.table.CompassState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMPASS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPASS_NORTH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMPASS_SOUTH', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=730,
  serialized_end=803,
)
_sym_db.RegisterEnumDescriptor(_COMPASSSTATE)

CompassState = enum_type_wrapper.EnumTypeWrapper(_COMPASSSTATE)
CUP_TYPE__UNKNOWN = 0
CUP_TYPE_GREEN = 1
CUP_TYPE_RED = 2
CUP_ORIENTATION_UNKNOWN = 0
CUP_ORIENTATION_STANDING = 1
CUP_ORIENTATION_UPTURNED = 2
WINDSOCK_UNKNOWN = 0
WINDSOCK_UP = 1
WINDSOCK_DOWN = 2
COMPASS_UNKNOWN = 0
COMPASS_NORTH = 1
COMPASS_SOUTH = 2



_CUPSTATE = _descriptor.Descriptor(
  name='CupState',
  full_name='goldo.table.CupState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='goldo.table.CupState.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='goldo.table.CupState.orientation', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='goldo.table.CupState.position', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=208,
)


_REEFSTATE = _descriptor.Descriptor(
  name='ReefState',
  full_name='goldo.table.ReefState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cups', full_name='goldo.table.ReefState.cups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=258,
)


_TABLESTATE_REEFSENTRY = _descriptor.Descriptor(
  name='ReefsEntry',
  full_name='goldo.table.TableState.ReefsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='goldo.table.TableState.ReefsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='goldo.table.TableState.ReefsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=474,
)

_TABLESTATE = _descriptor.Descriptor(
  name='TableState',
  full_name='goldo.table.TableState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reefs', full_name='goldo.table.TableState.reefs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cups', full_name='goldo.table.TableState.cups', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compas', full_name='goldo.table.TableState.compas', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TABLESTATE_REEFSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=474,
)

_CUPSTATE.fields_by_name['type'].enum_type = _CUPTYPE
_CUPSTATE.fields_by_name['orientation'].enum_type = _CUPORIENTATION
_CUPSTATE.fields_by_name['position'].message_type = goldo_dot_common_dot_geometry__pb2._POINT
_REEFSTATE.fields_by_name['cups'].message_type = _CUPSTATE
_TABLESTATE_REEFSENTRY.fields_by_name['value'].message_type = _REEFSTATE
_TABLESTATE_REEFSENTRY.containing_type = _TABLESTATE
_TABLESTATE.fields_by_name['reefs'].message_type = _TABLESTATE_REEFSENTRY
_TABLESTATE.fields_by_name['cups'].message_type = _CUPSTATE
_TABLESTATE.fields_by_name['compas'].enum_type = _COMPASSSTATE
DESCRIPTOR.message_types_by_name['CupState'] = _CUPSTATE
DESCRIPTOR.message_types_by_name['ReefState'] = _REEFSTATE
DESCRIPTOR.message_types_by_name['TableState'] = _TABLESTATE
DESCRIPTOR.enum_types_by_name['CupType'] = _CUPTYPE
DESCRIPTOR.enum_types_by_name['CupOrientation'] = _CUPORIENTATION
DESCRIPTOR.enum_types_by_name['WindsockState'] = _WINDSOCKSTATE
DESCRIPTOR.enum_types_by_name['CompassState'] = _COMPASSSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CupState = _reflection.GeneratedProtocolMessageType('CupState', (_message.Message,), dict(
  DESCRIPTOR = _CUPSTATE,
  __module__ = 'goldo.table_pb2'
  # @@protoc_insertion_point(class_scope:goldo.table.CupState)
  ))
_sym_db.RegisterMessage(CupState)

ReefState = _reflection.GeneratedProtocolMessageType('ReefState', (_message.Message,), dict(
  DESCRIPTOR = _REEFSTATE,
  __module__ = 'goldo.table_pb2'
  # @@protoc_insertion_point(class_scope:goldo.table.ReefState)
  ))
_sym_db.RegisterMessage(ReefState)

TableState = _reflection.GeneratedProtocolMessageType('TableState', (_message.Message,), dict(

  ReefsEntry = _reflection.GeneratedProtocolMessageType('ReefsEntry', (_message.Message,), dict(
    DESCRIPTOR = _TABLESTATE_REEFSENTRY,
    __module__ = 'goldo.table_pb2'
    # @@protoc_insertion_point(class_scope:goldo.table.TableState.ReefsEntry)
    ))
  ,
  DESCRIPTOR = _TABLESTATE,
  __module__ = 'goldo.table_pb2'
  # @@protoc_insertion_point(class_scope:goldo.table.TableState)
  ))
_sym_db.RegisterMessage(TableState)
_sym_db.RegisterMessage(TableState.ReefsEntry)


_TABLESTATE_REEFSENTRY._options = None
# @@protoc_insertion_point(module_scope)
