---
gpio:
  - id: 0
    name: nucleo_led
    pin: PA5
    mode: OUT_PP
  - id: 1
    name: nucleo_user_button
    pin: PC5
    mode: IN
    
timer:
  - device: TIM2
    prescaler: 1
    period: 10000
    
pwm:
  - id: 0
    name: test
    device: TIM2
    channel: CH1
    pin: PA5
    dir_pin: PB2

encoder:
  - id: 0
    name: left_encoder
    device: TIM1
    period: 8192
    ch1_pin: PA8
    ch2_pin: PA9
  - id: 1
    name: right_encoder
    device: TIM4
    period: 8192
    ch1_pin: PB6
    ch2_pin: PB7

uart:
  - name: uart_dynamixels
    device: USART1
    id: 2
    baudrate: 1000000
    rx_buffer_size: 256
    rx_blocking: false
    tx_blocking: true
    rx_dma: true
    tx_dma: true
    rx_pin: PA10
    tx_pin: PC4
    txen_pin: PC5
i2c:
  - id: 6
    name: i2c_tof
    device: I2C1
    timing: 0x10808DD3
    scl_pin: PB8
    sda_pin: PB9
spi:
  - name: spi_fpga
    device: SPI1
    id: 4
    sck_pin: PA5
    mosi_pin: PA7
    miso_pin: PA6
    baudrate_prescaler: 16
